### PR TITLE
wip! reserved keywords

### PR DESCRIPTION
**Pull request by chrisdickinson**
Just a quick rev on #17 – we can throw it away if we like!

(Additionally, I switched us over to `serde_json::Map` from `std::collections::HashMap`.)

I haven't tested these, but I can do so after rebasing on #16 if we're interested in this!

### CODE REVIEW

**Review by bhelx — APPROVED** [review]
Looks good to me. I like not littering the code with `r#` everywhere!

**Comment by chrisdickinson** [comment]
Thanks! I pushed up one more change that handles the (off-chance) that someone uses a reserved word as an export (`fn`)

(Edit: and rebased on top of #16)

**Comment by zshipko** [comment]
This looks good to me!

I am planning to look into why tests are failing this afternoon

**Review by zshipko — APPROVED** [review]
I just pushed a commit that fixes the bindgen tests locally, but not on CI :disappointed: 

We can merge this and I can debug CI on another branch

**Pull request merged**
